addr: ':8602'
application: "You Auth Service"
instance: "main"
datasource:
  sqlite:
    type: sqlite
    path: "./data/database.db"
service:
  name: "yas"
  display: "YouAuth service"
log:
  youlog:
    application: "YouAuth"
    instance: "main"
    engine:
      local:
        type: logrus
token:
  authCodeExpiresIn: 300
  refreshTokenExpiresIn: 2592000
  accessTokenExpiresIn: 2592000
#  accessTokenExpiresIn: 3
  appTokenExpiresIn: 864000000
  issuer: "youauth"
  secret: "aaabbbcccddd"
